# -*- coding: utf-8 -*-
"""modelo-base-atividade-agentes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wOcv6NVTKbdfySMaVj9DY-qCZvQT50Et

# Atividade de Fixação — Um ambiente, quatro agentes

**Universidade Federal do Piauí — UFPI**  
**Disciplina:** Inteligência Artificial  
**Professor:** Dr. Pedro Almir Martins de Oliveira  

**Matrícula:** 20249022029

**Estudante:** Gustavo Bastos Ribeiro Carvalho    

> **Pergunta norteadora:** quem toma as melhores decisões no controle de um cruzamento: o agente reflexivo simples, o agente baseado em modelo, o agente baseado em objetivos ou o agente baseado em utilidade? E, qual o impacto dessas decisões?

## 1. Objetivos de aprendizagem

Ao concluir esta atividade, você deverá ser capaz de:

1. implementar quatro arquiteturas de agentes inteligentes em um mesmo ambiente;
2. distinguir percepção, estado interno, objetivo e utilidade;
3. planejar um experimento controlado e reproduzível;
4. comparar agentes por meio de métricas, tabelas e gráficos;
5. justificar por que uma arquitetura se mostrou mais adequada ao problema.

### Entrega

- Faça uma cópia deste notebook no Google Colab.
- Preencha as células marcadas com **IMPLEMENTAÇÃO DO ESTUDANTE** e **ANÁLISE DO ESTUDANTE**.
- Execute o notebook inteiro antes da entrega.
- Entregue o link compartilhável do Colab, com códigos, resultados, gráficos e respostas preservados.
- Prazo: **duas semanas após a proposição da atividade**.

## 2. Problema proposto

O ambiente representa um cruzamento simplificado com dois fluxos:

- **Norte–Sul (NS)**;
- **Leste–Oeste (LO)**.

A cada passo de tempo, novos veículos podem chegar às duas filas. O agente controla o semáforo e escolhe uma entre duas ações:

- `MANTER`: conservar a direção atualmente verde;
- `TROCAR`: conceder sinal verde à outra direção.

O ambiente impede trocas antes de um tempo verde mínimo. Em cada passo, até um veículo da direção verde é atendido.

### Métricas principais

1. tempo médio de espera dos veículos atendidos;
2. maior fila formada;
3. quantidade de veículos atendidos;
4. número de trocas do semáforo.

Também serão registrados a fila final, a taxa de atendimento e o atraso acumulado por veículo que chegou. Essas métricas adicionais ajudam a identificar políticas que aparentemente reduzem a espera apenas porque deixam veículos sem atendimento.

## 3. Descrição PEAS

| Elemento | Definição neste problema |
|---|---|
| **Medida de desempenho** | Reduzir espera e filas, atender mais veículos e evitar trocas excessivas |
| **Ambiente** | Cruzamento, duas filas, chegadas estocásticas e passagem discreta do tempo |
| **Atuadores** | Manter ou trocar a direção verde |
| **Sensores** | Tamanho das filas, direção verde, tempo no sinal e espera do veículo mais antigo |

O ambiente é **sequencial**, **estocástico**, **dinâmico** e **discreto**. O agente observa as filas atuais, mas não conhece antecipadamente as próximas chegadas.

## 4. As quatro arquiteturas

| Arquitetura | Informação utilizada | Elemento distintivo | Exemplo de raciocínio |
|---|---|---|---|
| **Reflexivo simples** | Apenas a percepção atual | Regras condição–ação | “Se a fila fechada ultrapassou o limite, troque.” |
| **Baseado em modelo** | Percepção atual e estado interno | Memória da evolução do ambiente | “A fila LO está crescendo nos últimos passos; devo antecipar a troca.” |
| **Baseado em objetivos** | Estado atual, modelo das ações e meta explícita | Procura uma ação que alcance ou preserve um estado-meta | “Qual ação mantém as duas filas abaixo do limite?” |
| **Baseado em utilidade** | Estado atual, consequências estimadas e função numérica | Compara graus de preferência e compensações | “A redução de espera compensa o custo de mais uma troca?” |

## 5. Diferença essencial: objetivo × utilidade

Os dois agentes podem prever consequências antes de agir, mas **não avaliam as alternativas da mesma maneira**.

### Agente baseado em objetivos

Trabalha com uma condição que define se a meta foi alcançada. Por exemplo:

$$G(s) = [\max(fila_{NS}, fila_{LO}) \leq 8]$$

Um estado satisfaz ou não satisfaz a meta. O agente procura uma ação que leve a um estado aceitável. Se duas alternativas alcançarem a mesma meta, o objetivo, sozinho, pode não informar qual delas é melhor; será necessária uma regra de desempate.

### Agente baseado em utilidade

Atribui uma pontuação às consequências das ações. Por exemplo:

$$U(s,a) = -(2E + 1{,}5F + 0{,}4T + 0{,}7D)$$

Em que:

- $E$ é a espera estimada;
- $F$ é a maior fila estimada;
- $T$ indica o custo de trocar o sinal;
- $D$ é o desequilíbrio entre as filas.

Quanto maior a utilidade, mais desejável é a alternativa. A função permite escolher entre diferentes estados aceitáveis e realizar **trade-offs**. Uma troca pode aumentar o custo operacional, mas ainda ser escolhida se reduzir suficientemente a espera e o tamanho das filas.

> **Resumo:** objetivo responde principalmente **“a meta será atingida?”**; utilidade responde **“entre as alternativas possíveis, qual resultado é preferível e quanto?”**.
"""

# FORNECIDO PELO PROFESSOR — execute, mas não modifique
import math
from collections import deque
from dataclasses import dataclass, asdict
from enum import Enum
from typing import Callable, Dict, Iterable, List, Tuple

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None)
plt.style.use("seaborn-v0_8-whitegrid")

print("Ambiente preparado.")

"""## 6. Tipos e configurações do ambiente

As células identificadas como **FORNECIDO PELO PROFESSOR** constituem a infraestrutura comum do experimento. Não as altere: a padronização é necessária para comparar os resultados.
"""

# FORNECIDO PELO PROFESSOR — execute, mas não modifique
class Direcao(str, Enum):
    NS = "NS"
    LO = "LO"


class Acao(str, Enum):
    MANTER = "MANTER"
    TROCAR = "TROCAR"


@dataclass(frozen=True)
class Percepcao:
    tempo: int
    fila_ns: int
    fila_lo: int
    verde: Direcao
    tempo_no_verde: int
    espera_mais_antiga_ns: int
    espera_mais_antiga_lo: int


@dataclass(frozen=True)
class ConfiguracaoSimulacao:
    duracao: int = 240
    capacidade_por_passo: int = 1
    verde_minimo: int = 3
    verde_inicial: Direcao = Direcao.NS


@dataclass(frozen=True)
class CenarioTrafego:
    semente: int
    chegadas_ns: np.ndarray
    chegadas_lo: np.ndarray


CONFIG = ConfiguracaoSimulacao()
CONFIG

# FORNECIDO PELO PROFESSOR — execute, mas não modifique
def gerar_cenario_trafego(semente: int, duracao: int = CONFIG.duracao) -> CenarioTrafego:
    """Gera chegadas reproduzíveis com três regimes de tráfego.

    1º terço: maior fluxo NS; 2º terço: maior fluxo LO;
    3º terço: fluxos equilibrados.
    """
    rng = np.random.default_rng(semente)
    corte_1, corte_2 = duracao // 3, 2 * duracao // 3

    taxa_ns = np.full(duracao, 0.45, dtype=float)
    taxa_lo = np.full(duracao, 0.45, dtype=float)
    taxa_ns[:corte_1], taxa_lo[:corte_1] = 0.65, 0.25
    taxa_ns[corte_1:corte_2], taxa_lo[corte_1:corte_2] = 0.25, 0.65

    chegadas_ns = rng.poisson(taxa_ns)
    chegadas_lo = rng.poisson(taxa_lo)
    return CenarioTrafego(semente, chegadas_ns, chegadas_lo)


def visualizar_cenario(cenario: CenarioTrafego) -> None:
    janela = 12
    ns = pd.Series(cenario.chegadas_ns).rolling(janela, min_periods=1).mean()
    lo = pd.Series(cenario.chegadas_lo).rolling(janela, min_periods=1).mean()
    plt.figure(figsize=(11, 3.5))
    plt.plot(ns, label="NS — média móvel de chegadas")
    plt.plot(lo, label="LO — média móvel de chegadas")
    plt.xlabel("Passo de tempo")
    plt.ylabel("Chegadas por passo")
    plt.title(f"Cenário de tráfego — semente {cenario.semente}")
    plt.legend()
    plt.show()


cenario_exemplo = gerar_cenario_trafego(2026)
visualizar_cenario(cenario_exemplo)

"""## 7. Interface comum dos agentes

Todos os agentes devem implementar os mesmos dois métodos:

- `reiniciar()`: apaga o estado interno antes de uma nova simulação;
- `decidir(percepcao)`: devolve `Acao.MANTER` ou `Acao.TROCAR`.

A comparação será justa porque somente a política de decisão muda. O ambiente, as chegadas e as métricas permanecem iguais.
"""

# FORNECIDO PELO PROFESSOR — execute, mas não modifique
class AgenteBase:
    nome = "Agente base"

    def reiniciar(self) -> None:
        """Reinicia o agente antes de uma execução independente."""
        pass

    def decidir(self, percepcao: Percepcao) -> Acao:
        raise NotImplementedError


def normalizar_acao(acao) -> Acao:
    if isinstance(acao, Acao):
        return acao
    try:
        return Acao(str(acao).upper())
    except ValueError as erro:
        raise ValueError(
            f"Ação inválida: {acao!r}. Retorne Acao.MANTER ou Acao.TROCAR."
        ) from erro


def direcao_oposta(direcao: Direcao) -> Direcao:
    return Direcao.LO if direcao == Direcao.NS else Direcao.NS


def estimar_filas_apos_acao(
    percepcao: Percepcao,
    acao: Acao,
    capacidade: int = CONFIG.capacidade_por_passo,
    verde_minimo: int = CONFIG.verde_minimo,
) -> Tuple[int, int]:
    """Estimativa de um passo, sem conhecer as próximas chegadas."""
    acao = normalizar_acao(acao)
    troca_permitida = percepcao.tempo_no_verde >= verde_minimo
    verde_estimado = percepcao.verde
    if acao == Acao.TROCAR and troca_permitida:
        verde_estimado = direcao_oposta(percepcao.verde)

    fila_ns, fila_lo = percepcao.fila_ns, percepcao.fila_lo
    if verde_estimado == Direcao.NS:
        fila_ns = max(0, fila_ns - capacidade)
    else:
        fila_lo = max(0, fila_lo - capacidade)
    return fila_ns, fila_lo

# FORNECIDO PELO PROFESSOR — execute, mas não modifique
def simular(
    agente: AgenteBase,
    cenario: CenarioTrafego,
    config: ConfiguracaoSimulacao = CONFIG,
    guardar_historico: bool = False,
) -> Tuple[Dict[str, float], pd.DataFrame]:
    """Executa um agente em um cenário de tráfego previamente gerado."""
    agente.reiniciar()
    fila_ns, fila_lo = deque(), deque()
    verde = config.verde_inicial
    tempo_no_verde = 0
    trocas = 0
    atendidos = 0
    esperas_atendidos: List[int] = []
    maior_fila_ns = maior_fila_lo = 0
    atraso_acumulado = 0
    historico = []

    for tempo in range(config.duracao):
        for _ in range(int(cenario.chegadas_ns[tempo])):
            fila_ns.append(tempo)
        for _ in range(int(cenario.chegadas_lo[tempo])):
            fila_lo.append(tempo)

        maior_fila_ns = max(maior_fila_ns, len(fila_ns))
        maior_fila_lo = max(maior_fila_lo, len(fila_lo))

        percepcao = Percepcao(
            tempo=tempo,
            fila_ns=len(fila_ns),
            fila_lo=len(fila_lo),
            verde=verde,
            tempo_no_verde=tempo_no_verde,
            espera_mais_antiga_ns=(tempo - fila_ns[0]) if fila_ns else 0,
            espera_mais_antiga_lo=(tempo - fila_lo[0]) if fila_lo else 0,
        )
        acao_solicitada = normalizar_acao(agente.decidir(percepcao))
        troca_executada = (
            acao_solicitada == Acao.TROCAR
            and tempo_no_verde >= config.verde_minimo
        )

        if troca_executada:
            verde = direcao_oposta(verde)
            trocas += 1
            tempo_no_verde = 0

        fila_aberta = fila_ns if verde == Direcao.NS else fila_lo
        for _ in range(min(config.capacidade_por_passo, len(fila_aberta))):
            chegada = fila_aberta.popleft()
            esperas_atendidos.append(tempo - chegada)
            atendidos += 1

        atraso_acumulado += len(fila_ns) + len(fila_lo)
        tempo_no_verde += 1
        maior_fila_ns = max(maior_fila_ns, len(fila_ns))
        maior_fila_lo = max(maior_fila_lo, len(fila_lo))

        if guardar_historico:
            historico.append({
                "tempo": tempo,
                "fila_ns": len(fila_ns),
                "fila_lo": len(fila_lo),
                "verde": verde.value,
                "acao_solicitada": acao_solicitada.value,
                "troca_executada": troca_executada,
                "atendidos_acumulados": atendidos,
            })

    total_chegadas = int(cenario.chegadas_ns.sum() + cenario.chegadas_lo.sum())
    fila_final = len(fila_ns) + len(fila_lo)
    assert atendidos + fila_final == total_chegadas, "Falha na conservação de veículos."

    metricas = {
        "semente": cenario.semente,
        "agente": agente.nome,
        "tempo_medio_espera": float(np.mean(esperas_atendidos)) if esperas_atendidos else 0.0,
        "maior_fila": max(maior_fila_ns, maior_fila_lo),
        "veiculos_atendidos": atendidos,
        "numero_trocas": trocas,
        "fila_final": fila_final,
        "taxa_atendimento": atendidos / total_chegadas if total_chegadas else 1.0,
        "atraso_medio_por_chegada": atraso_acumulado / total_chegadas if total_chegadas else 0.0,
        "total_chegadas": total_chegadas,
    }
    return metricas, pd.DataFrame(historico)

"""## 8. Verificação do ambiente fornecido

Este teste usa dois agentes auxiliares muito simples. Ele verifica a reprodução por semente e a conservação da quantidade de veículos.
"""

# FORNECIDO PELO PROFESSOR — execute, mas não modifique
class _AgenteSempreManter(AgenteBase):
    nome = "Auxiliar — sempre manter"

    def decidir(self, percepcao: Percepcao) -> Acao:
        return Acao.MANTER


def testar_ambiente() -> None:
    cenario_a = gerar_cenario_trafego(123)
    cenario_b = gerar_cenario_trafego(123)
    assert np.array_equal(cenario_a.chegadas_ns, cenario_b.chegadas_ns)
    assert np.array_equal(cenario_a.chegadas_lo, cenario_b.chegadas_lo)

    m1, _ = simular(_AgenteSempreManter(), cenario_a)
    m2, _ = simular(_AgenteSempreManter(), cenario_b)
    assert m1 == m2, "A mesma semente deve produzir o mesmo resultado."
    assert m1["veiculos_atendidos"] + m1["fila_final"] == m1["total_chegadas"]
    print("✓ Ambiente determinístico por semente e contabilização consistente.")


testar_ambiente()

"""# PARTE I — Implementação dos agentes

Implemente as quatro classes a seguir. Você pode criar métodos auxiliares dentro das classes, mas não deve alterar seus nomes, construtores ou interfaces públicas.

As políticas devem respeitar o tempo verde mínimo: solicitar uma troca antes desse limite não produz efeito no ambiente.
"""

# IMPLEMENTAÇÃO DO ESTUDANTE — Agente 1
class AgenteReflexivoSimples(AgenteBase):
    nome = "Reflexivo simples"

    def __init__(self, limite_fila_fechada: int = 6):
        self.limite_fila_fechada = limite_fila_fechada

    def decidir(self, percepcao: Percepcao) -> Acao:
        """Use somente os dados da percepção atual e regras condição–ação.

        Sugestão: identifique a fila da direção fechada e compare-a com o
        limite. Não armazene histórico neste agente.
        """
        fila_fechada = (
            percepcao.fila_lo if percepcao.verde == Direcao.NS else percepcao.fila_ns
        )
        if fila_fechada > self.limite_fila_fechada:
            return Acao.TROCAR
        return Acao.MANTER

# IMPLEMENTAÇÃO DO ESTUDANTE — Agente 2
class AgenteBaseadoModelo(AgenteBase):
    nome = "Baseado em modelo"

    def __init__(self, janela: int = 5, limite_fila_fechada: int = 6):
        self.janela = janela
        self.limite_fila_fechada = limite_fila_fechada
        self.reiniciar()

    def reiniciar(self) -> None:
        # Estas listas constituem parte do estado interno do agente.
        self.historico_ns: List[int] = []
        self.historico_lo: List[int] = []

    def decidir(self, percepcao: Percepcao) -> Acao:
        """Atualize o estado interno e use a evolução recente das filas.

        Uma possibilidade é calcular tendências: diferença entre valores
        recentes, média móvel ou número de passos consecutivos de crescimento.
        Sua decisão não deve depender apenas da percepção instantânea.
        """
        self.historico_lo.append(percepcao.fila_lo)
        self.historico_ns.append(percepcao.fila_ns)

        if len(self.historico_lo) > self.janela:
            self.historico_lo.pop(0)
        if len(self.historico_ns) > self.janela:
            self.historico_ns.pop(0)

        if percepcao.verde == Direcao.NS:
            historico_fechada = self.historico_lo
        else:
            historico_fechada = self.historico_ns

        media_fechada = sum(historico_fechada) / len(historico_fechada)

        tendencia_fila_fechada = historico_fechada[-1] - historico_fechada[0]

        if media_fechada > self.limite_fila_fechada:
            return Acao.TROCAR

        if media_fechada > self.limite_fila_fechada * 0.75 and tendencia_fila_fechada > 0:
            return Acao.TROCAR
        return Acao.MANTER

# IMPLEMENTAÇÃO DO ESTUDANTE — Agente 3
class AgenteBaseadoObjetivos(AgenteBase):
    nome = "Baseado em objetivos"

    def __init__(self, limite_meta: int = 8):
        self.limite_meta = limite_meta

    def meta_satisfeita(self, fila_ns: int, fila_lo: int) -> bool:
        """Retorne True quando as duas filas estiverem dentro da meta."""
        # TODO: implemente a condição-meta apresentada na seção 5.
        raise NotImplementedError("Implemente a condição de objetivo.")

    def decidir(self, percepcao: Percepcao) -> Acao:
        """Compare as consequências estimadas de MANTER e TROCAR.

        Use estimar_filas_apos_acao(). Se somente uma ação satisfizer a meta,
        escolha-a. Se ambas satisfizerem, use MANTER como desempate. Se nenhuma
        satisfizer, escolha a que produzir menor violação do limite.
        """
        # TODO: avalie as duas ações em função da meta explícita.
        
        raise NotImplementedError("Implemente o agente baseado em objetivos.")

# IMPLEMENTAÇÃO DO ESTUDANTE — Agente 4
class AgenteBaseadoUtilidade(AgenteBase):
    nome = "Baseado em utilidade"

    def __init__(
        self,
        peso_fila_total: float = 1.0,
        peso_maior_fila: float = 1.5,
        peso_espera: float = 2.0,
        custo_troca: float = 0.4,
        peso_desequilibrio: float = 0.7,
    ):
        self.peso_fila_total = peso_fila_total
        self.peso_maior_fila = peso_maior_fila
        self.peso_espera = peso_espera
        self.custo_troca = custo_troca
        self.peso_desequilibrio = peso_desequilibrio

    def calcular_utilidade(self, percepcao: Percepcao, acao: Acao) -> float:
        """Calcule uma pontuação: valores maiores representam melhores ações.

        Use as filas retornadas por estimar_filas_apos_acao() e combine:
        fila total, maior fila, espera mais antiga, desequilíbrio e custo da
        troca. Documente qualquer adaptação da fórmula.

        Extensão em relação à fórmula da seção 5: além de espera (E), maior
        fila (F), custo de troca (T) e desequilíbrio (D), também penaliza a
        fila total estimada (FT), evitando que o agente ignore o volume
        agregado de veículos ao comparar as duas ações.
        """
        acao = normalizar_acao(acao)
        fila_ns_est, fila_lo_est = estimar_filas_apos_acao(percepcao, acao)

        fila_total = fila_ns_est + fila_lo_est
        maior_fila = max(fila_ns_est, fila_lo_est)
        desequilibrio = abs(fila_ns_est - fila_lo_est)

        troca_efetiva = (
            acao == Acao.TROCAR and percepcao.tempo_no_verde >= CONFIG.verde_minimo
        )
        verde_estimado = direcao_oposta(percepcao.verde) if troca_efetiva else percepcao.verde
        direcao_fechada = direcao_oposta(verde_estimado)
        espera = (
            percepcao.espera_mais_antiga_ns
            if direcao_fechada == Direcao.NS
            else percepcao.espera_mais_antiga_lo
        )

        custo = self.custo_troca if troca_efetiva else 0.0

        return -(
            self.peso_fila_total * fila_total
            + self.peso_maior_fila * maior_fila
            + self.peso_espera * espera
            + self.peso_desequilibrio * desequilibrio
            + custo
        )

    def decidir(self, percepcao: Percepcao) -> Acao:
        """Escolha a ação com maior utilidade; use MANTER no empate."""
        utilidade_manter = self.calcular_utilidade(percepcao, Acao.MANTER)
        utilidade_trocar = self.calcular_utilidade(percepcao, Acao.TROCAR)
        if utilidade_trocar > utilidade_manter:
            return Acao.TROCAR
        return Acao.MANTER

"""## 9. Testes automáticos das implementações

Os testes abaixo verificam requisitos mínimos, mas não garantem que a política seja ótima. Uma implementação pode passar em todos os testes e ainda tomar decisões ruins em determinados cenários.

Durante a correção poderão ser usados outros casos de teste com a mesma interface.
"""

# FORNECIDO PELO PROFESSOR — execute, mas não modifique
def _registrar_teste(nome: str, funcao: Callable[[], None]) -> bool:
    try:
        funcao()
        print(f"✓ {nome}")
        return True
    except Exception as erro:
        print(f"✗ {nome}: {type(erro).__name__} — {erro}")
        return False


def _percepcoes_teste() -> List[Percepcao]:
    return [
        Percepcao(10, 2, 12, Direcao.NS, 5, 1, 8),
        Percepcao(20, 9, 1, Direcao.LO, 6, 7, 0),
        Percepcao(30, 3, 3, Direcao.NS, 1, 2, 2),
    ]


def teste_interface_todos() -> None:
    agentes = [
        AgenteReflexivoSimples(),
        AgenteBaseadoModelo(),
        AgenteBaseadoObjetivos(),
        AgenteBaseadoUtilidade(),
    ]
    for agente in agentes:
        agente.reiniciar()
        for percepcao in _percepcoes_teste():
            acao = normalizar_acao(agente.decidir(percepcao))
            assert acao in (Acao.MANTER, Acao.TROCAR)


def teste_memoria_modelo() -> None:
    agente = AgenteBaseadoModelo(janela=3)
    agente.reiniciar()
    assert agente.historico_ns == [] and agente.historico_lo == []
    for percepcao in _percepcoes_teste():
        agente.decidir(percepcao)
    assert len(agente.historico_ns) > 0 and len(agente.historico_lo) > 0, (
        "O agente baseado em modelo deve atualizar seu estado interno."
    )
    agente.reiniciar()
    assert agente.historico_ns == [] and agente.historico_lo == [], (
        "reiniciar() deve apagar o estado interno."
    )


def teste_objetivo_expresso() -> None:
    agente = AgenteBaseadoObjetivos(limite_meta=8)
    assert agente.meta_satisfeita(8, 7)
    assert not agente.meta_satisfeita(9, 2)
    # MANTER deixa LO=9; TROCAR atende LO e leva a fila a 8: somente TROCAR atinge a meta.
    p = Percepcao(10, 1, 9, Direcao.NS, 5, 0, 6)
    assert normalizar_acao(agente.decidir(p)) == Acao.TROCAR
    # As duas alternativas preservam a meta: o desempate solicitado é MANTER.
    p_empate = Percepcao(11, 2, 2, Direcao.NS, 5, 1, 1)
    assert normalizar_acao(agente.decidir(p_empate)) == Acao.MANTER


def teste_utilidade_consistente() -> None:
    agente = AgenteBaseadoUtilidade()
    p = Percepcao(15, 2, 10, Direcao.NS, 5, 1, 7)
    u_manter = agente.calcular_utilidade(p, Acao.MANTER)
    u_trocar = agente.calcular_utilidade(p, Acao.TROCAR)
    assert math.isfinite(u_manter) and math.isfinite(u_trocar)
    esperada = Acao.MANTER if u_manter >= u_trocar else Acao.TROCAR
    assert normalizar_acao(agente.decidir(p)) == esperada, (
        "decidir() deve selecionar a ação de maior utilidade."
    )


def executar_testes_dos_agentes() -> bool:
    testes = [
        ("Interface comum dos quatro agentes", teste_interface_todos),
        ("Estado interno do agente baseado em modelo", teste_memoria_modelo),
        ("Meta explícita do agente baseado em objetivos", teste_objetivo_expresso),
        ("Escolha coerente do agente baseado em utilidade", teste_utilidade_consistente),
    ]
    resultados = [_registrar_teste(nome, funcao) for nome, funcao in testes]
    aprovados = sum(resultados)
    print(f"\nResultado: {aprovados}/{len(resultados)} testes aprovados.")
    return all(resultados)


IMPLEMENTACOES_PRONTAS = executar_testes_dos_agentes()

"""### Explique suas decisões de projeto — ANÁLISE DO ESTUDANTE

Preencha esta célula antes de executar o experimento:

1. **Reflexivo simples:** quais regras condição–ação e qual limite você utilizou?  
   **Resposta:** ...

2. **Baseado em modelo:** qual estado interno foi mantido e como ele influenciou as decisões?  
   **Resposta:** ...

3. **Baseado em objetivos:** qual é a meta e o que ocorre quando nenhuma ação consegue satisfazê-la imediatamente?  
   **Resposta:** ...

4. **Baseado em utilidade:** apresente a fórmula e justifique os pesos. Que compensações ela permite realizar?  
   **Resposta:** ...

# PARTE II — Protocolo experimental

Serão usadas **30 sementes**. Para cada semente, o tráfego é gerado uma única vez e reutilizado pelos quatro agentes. Temos, portanto, um experimento pareado:

- semente 0 → mesma sequência para os quatro agentes;
- semente 1 → mesma sequência para os quatro agentes;
- ...
- semente 29 → mesma sequência para os quatro agentes.

Isso evita atribuir ao agente uma vantagem causada por um cenário aleatoriamente mais fácil.
"""

# FORNECIDO PELO PROFESSOR — execute, mas não modifique
def executar_protocolo(
    fabricas: Dict[str, Callable[[], AgenteBase]],
    sementes: Iterable[int],
) -> pd.DataFrame:
    registros = []
    for semente in sementes:
        cenario = gerar_cenario_trafego(semente)
        for _, fabrica in fabricas.items():
            metricas, _ = simular(fabrica(), cenario)
            registros.append(metricas)
    return pd.DataFrame(registros)


def resumir_resultados(resultados: pd.DataFrame) -> pd.DataFrame:
    metricas = [
        "tempo_medio_espera",
        "maior_fila",
        "veiculos_atendidos",
        "numero_trocas",
        "fila_final",
        "taxa_atendimento",
        "atraso_medio_por_chegada",
    ]
    resumo = resultados.groupby("agente")[metricas].agg(["mean", "std"])
    return resumo.round(3)


FABRICAS_AGENTES = {
    "reflexivo": lambda: AgenteReflexivoSimples(),
    "modelo": lambda: AgenteBaseadoModelo(),
    "objetivos": lambda: AgenteBaseadoObjetivos(),
    "utilidade": lambda: AgenteBaseadoUtilidade(),
}
SEMENTES = range(30)

if IMPLEMENTACOES_PRONTAS:
    resultados = executar_protocolo(FABRICAS_AGENTES, SEMENTES)
    print(f"Experimento concluído: {len(resultados)} execuções.")
    display(resumir_resultados(resultados))
else:
    resultados = pd.DataFrame()
    print("Conclua as implementações e aprove os testes antes do experimento.")

# FORNECIDO PELO PROFESSOR — execute, mas não modifique
def plotar_comparacao(resultados: pd.DataFrame) -> None:
    if resultados.empty:
        print("Ainda não há resultados para representar.")
        return

    metricas = [
        ("tempo_medio_espera", "Tempo médio de espera ↓"),
        ("maior_fila", "Maior fila ↓"),
        ("veiculos_atendidos", "Veículos atendidos ↑"),
        ("numero_trocas", "Número de trocas ↓"),
    ]
    agentes = list(resultados["agente"].unique())
    fig, eixos = plt.subplots(2, 2, figsize=(13, 8))

    for eixo, (coluna, titulo) in zip(eixos.ravel(), metricas):
        dados = [resultados.loc[resultados["agente"] == a, coluna] for a in agentes]
        eixo.boxplot(dados, tick_labels=agentes, showmeans=True)
        eixo.set_title(titulo)
        eixo.tick_params(axis="x", rotation=18)
        eixo.set_xlabel("")

    fig.suptitle("Distribuição dos resultados nas 30 sementes", fontsize=15)
    fig.tight_layout()
    plt.show()


plotar_comparacao(resultados)

"""## 10. Inspeção de uma execução

Escolha uma semente e observe passo a passo o comportamento dos agentes. Esse recurso ajuda a explicar resultados agregados e a localizar decisões inesperadas.
"""

# ANÁLISE DO ESTUDANTE — você pode modificar a semente e o agente
SEMENTE_INSPECAO = 7
AGENTE_INSPECAO = AgenteBaseadoUtilidade()

if IMPLEMENTACOES_PRONTAS:
    metricas_inspecao, historico_inspecao = simular(
        AGENTE_INSPECAO,
        gerar_cenario_trafego(SEMENTE_INSPECAO),
        guardar_historico=True,
    )
    display(pd.Series(metricas_inspecao, name="valor").to_frame())
    display(historico_inspecao.head(15))

    historico_inspecao.plot(
        x="tempo",
        y=["fila_ns", "fila_lo"],
        figsize=(12, 3.5),
        title=f"Filas ao longo do tempo — {AGENTE_INSPECAO.nome}",
    )
    plt.ylabel("Veículos na fila")
    plt.show()
else:
    print("Conclua as implementações para inspecionar uma execução.")

"""# PARTE III — Análise dos resultados

## 11. Comparação crítica — ANÁLISE DO ESTUDANTE

Responda com base nas tabelas, nos gráficos e na inspeção de pelo menos uma execução:

1. Qual agente apresentou o melhor desempenho geral? Não responda somente pelo nome: indique as métricas que sustentam sua conclusão.  
   **Resposta:** ...

2. Algum agente foi melhor em uma métrica e pior em outra? Explique os trade-offs observados.  
   **Resposta:** ...

3. Qual arquitetura foi mais estável entre as sementes? Relacione sua resposta à dispersão dos resultados.  
   **Resposta:** ...

4. O estado interno melhorou as decisões do agente baseado em modelo? Apresente uma evidência.  
   **Resposta:** ...

5. Compare diretamente os agentes baseado em objetivos e baseado em utilidade. Identifique uma situação em que eles tomaram decisões diferentes e explique a causa conceitual dessa diferença.  
   **Resposta:** ...

6. A função de utilidade escolhida representa adequadamente o problema? Como os pesos alteram o comportamento do agente?  
   **Resposta:** ...

7. Quais simplificações do simulador limitam a generalização das conclusões para um cruzamento real?  
   **Resposta:** ...

## 12. Conclusão — ANÁLISE DO ESTUDANTE

Escreva entre 150 e 250 palavras respondendo à pergunta norteadora: **quem tomou as melhores decisões e, principalmente, por quê?**

Sua conclusão deve relacionar:

- arquitetura do agente;
- informações utilizadas na decisão;
- métricas obtidas;
- comportamento observado;
- limitações do experimento.

**Conclusão:** ...

## 13. Critérios de avaliação

| Critério | Pontuação |
|---|---:|
| Correção e organização das quatro implementações | 30 |
| Coerência entre implementação e arquitetura do agente | 25 |
| Protocolo experimental e reprodução dos resultados | 15 |
| Qualidade da análise, dos gráficos e da conclusão | 25 |
| Organização, clareza e execução integral do notebook | 5 |
| **Total** | **100** |

### Checklist antes da entrega

- [ ] Todos os testes foram aprovados.
- [ ] O protocolo produziu 120 execuções: 4 agentes × 30 sementes.
- [ ] A tabela-resumo e os quatro gráficos estão visíveis.
- [ ] As quatro decisões de projeto foram explicadas.
- [ ] Todas as perguntas da análise foram respondidas.
- [ ] A diferença entre objetivo e utilidade foi discutida com uma evidência experimental.
- [ ] O notebook foi executado do início ao fim e salvo com as saídas.
"""